### PR TITLE
Replaced Async by AsyncCreateble

### LINKED ISSUE #116: User unable to enter a location (if the location not found via autocomplete)
I was trying out the new version of the component. While its so cool to use react-select. But at the same time this choice some how forced wrong assumption

**The Wrong Assumption:** 
All addresses can be found via AutoComplete 

**Why Its Wrong ?** 
Because at least in my country (Austria) there is too many places which can't be found on google maps and thus they cannot be available within the options and thus the user can't choose them 

**Possible solutions:** 
using createable react-select but this will be very confusing for users (Because an address field should be an input field from user point of view and this is the common pattern. Its very uncommon to be a select field and upon that with "Create option")

### PR DESCRIPTION
**Pull request by bahaa-kallas**
fix #116 
making this the default behaviour just like how it was in the previous versions

### CODE REVIEW

**Comment by Tintef** [comment]
@bahaa-kallas My only concern here is how this will work when using the select as multi-select and selecting "real" values 🤔

**Comment by akamud** [comment]
Hi, we are also needing this same functionality. Is there anything blocking this PR?

**Comment by Tintef** [comment]
@akamud It looks like @bahaa-kallas never answered my question, and also never changed this to an actual PR (it's currently a draft PR).

Feel free to submit another PR (it looks fairly simple to do). If you don't, I'll try to do it over the weekend.

**Comment by bahaa-kallas** [comment]
Sorry for leaving this behind almost forgot about it until I checked my email and saw the notification.
I am closing it so someone else can work on it. 
bty In my company we reverted back to the old version as it was perfectly match our needs which was the reason that made me forget about completing this PR

**Pull request closed without merging**
