### PR TITLE
Add locationBias and locationRestriction

### PR DESCRIPTION
**Pull request by sceka**
Since location, bounds and radius are depricated from May 2023 and in Google Documentation is now locationBias and LocationRestriction,  I am creating this PR adding that and addditional types for those two

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Review by melloware — APPROVED** [review]

**Review by Tintef — CHANGES_REQUESTED** [review]
Hello @sceka. I can't merge this as the `package.json` changes are basically changing this library name, author, repository URL, etc.

**Comment by wobsoriano** [comment]
I believe next types release will have the `locationBias` based on this commit https://github.com/googlemaps/js-types/commit/9a7dc2a3eb0baeb1e2d299a199fa96bb343866f0

**Comment by Tintef** [comment]
Hey,I had some free time and was able to put this up on [a new PR](https://github.com/Tintef/react-google-places-autocomplete/pull/353). Will close this one as it's outdated and @sceka hasn't responded.

**Comment by sceka** [comment]
Hello,
Sorry for the late reply.

Thanks for making changes and opening new PR for me.

Thanks,
Marko

**Pull request closed without merging**
